# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-02 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0002_user_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='addresses.Addresses', verbose_name='默认地址'),
        ),
    ]
